### ISSUE TITLE
Test failure on Twisted 13.2 (and probably earlier)

### ISSUE THREAD

**Issue by mithrandi** [twisted/nevow#41]
PR #30 changed the log message format in `nevow.test.test_appserver.Logging.test_oldStyle` to match the format in Twisted 14.0. Unfortunately, this does not match the format used in earlier versions of Twisted, leading to this test failure:

```
[FAIL]
Traceback (most recent call last):
  File "/«PKGBUILDDIR»/debian/python-nevow/usr/lib/python2.7/site-packages/nevow/test/test_appserver.py", line 193, in test_oldStyle
    ['"fakeaddress2" - - faketime "GET /foo HTTP/1.0" 200 6 '
  File "/usr/lib/python2.7/dist-packages/twisted/trial/_synctest.py", line 356, in assertEqual
    % (msg, pformat(first), pformat(second)))
twisted.trial.unittest.FailTest: not equal:
a = ['fakeaddress2 - - faketime "GET /foo HTTP/1.0" 200 6 "fakerefer" "fakeagent"']
b = ['"fakeaddress2" - - faketime "GET /foo HTTP/1.0" 200 6 "fakerefer" "fakeagent"']


nevow.test.test_appserver.Logging.test_oldStyle
```

**Comment by mithrandi** [comment]
I think this is fixed.
